### ISSUE TITLE
Not working with new V2 agent (2.0.0.0ubuntu16.56)

### ISSUE THREAD

**Issue by jfarschman** [threatstack/threatstack-formula#18]
I use Saltstack to manage threatstack and ran into a an issue where my systems will not start after upgrading from 1.9 to 2.0.

Specifically, after running the state.apply threatstack it updated my minion to run 2.0.0.0ubuntu16.56 but was unable to handle the tsagent configuration change or the service restart.  Instead I get 
```----------
          ID: tsagent-config
    Function: cmd.wait
        Name: tsagent config log_level=debug
      Result: False
     Comment: Command "tsagent config log_level=debug" run
     Started: 09:19:39.352452
    Duration: 26.25 ms
     Changes:   
              ----------
              pid:
                  28103
              retcode:
                  1
              stderr:
                  tsagent: No option provided to config command
              stdout:
----------
          ID: threatstack
    Function: service.running
      Result: False
     Comment: One or more requisite failed: threatstack.tsagent-config
     Started: 09:19:40.203444
    Duration: 0.024 ms
     Changes:   ```

My pillar looks like this 
```
deploy_key: "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn"
ts_configure: True
ts_agent_latest: True
ts_agent_config_args: 'log_level=debug'
ts_agent_extra_args: --ruleset="Base Rule Set" 
```

**Comment by olhado** [comment]
The format of `tsagent config` and `tsagent setup` arguments has changed between 1.X and 2.X. For some examples/a trnslation guide, see: https://threatstack.zendesk.com/hc/en-us/articles/360022107271-Agent-1-x-series-vs-Agent-2-x-series-Commands

For `ts_agent_config_args` for your input, I believe it should be something like `--set log_level debug`

**Comment by jfarschman** [comment]
olhado,

You are correct. `ts_agent_config_args: '--set log.level debug'` did the trick.  I guess I"ll have to update all my systems to a 2.0.0.0 agent soon.

Thank you.

**Comment by jfarschman** [comment]
I'm closing.
