### ISSUE TITLE
Agent Version Does not take in to account Threatstack OS requirements

### ISSUE THREAD

**Issue by ssoto2** [threatstack/threatstack-formula#21]
Unfortunately, the outlined document from threatstack states that some OS versions can not support the 2.x agent. https://threatstack.zendesk.com/hc/en-us/articles/200343805

![Selection_074](https://user-images.githubusercontent.com/5123879/69670479-ec595f00-108b-11ea-9a60-d9971c5c3fb8.png)

the picture above showing an example where centos 6 does not support the 2.x agent

yet the init.sls initial step of determining the boolean for repository choosing does not intuitively determine if the OS can support that version. Many customers have fleets with multiple versions of an OS that need to be managed. considering Salt's use of grains the init.sls should be able to choose correctly. 

```
# Determine if we are installing agent 1.x or agent 2.x
{% if (pillar['ts_agent_latest'] is defined and pillar['ts_agent_latest'] == True) or (pillar['ts_agent_version'] is defined and pillar['ts_agent_version'].startswith('2.')) %}
  {% set install_agent2 = True %}
{% else %}
  {% set install_agent2 = False %}
{% endif %}
```

The line above dictates the repo

```
# Allow for package repo override from pillar
{% if pillar['pkg_url'] is defined %}
    {% set pkg_url = pillar['pkg_url'] %}
{% else %}
    {% if install_agent2 == True %}
      {% set pkg_url_base = 'https://pkg.threatstack.com/v2' %}
    {% else %}
      {% set pkg_url_base = 'https://pkg.threatstack.com' %}
    {% endif %}

```

**recommended resolution:** 

remove the following 

```
# Determine if we are installing agent 1.x or agent 2.x
{% if (pillar['ts_agent_latest'] is defined and pillar['ts_agent_latest'] == True) or (pillar['ts_agent_version'] is defined and pillar['ts_agent_version'].startswith('2.')) %}
  {% set install_agent2 = True %}
{% else %}
  {% set install_agent2 = False %}
{% endif %}
```

extend 

```
    {% set pkg_maj_ver = grains['osmajorrelease'] %}
    {% if grains['os_family']=="Debian" %}
      {% set pkg_url = [pkg_url_base, 'Ubuntu']|join('/') %}
    {% elif grains['os']=="Amazon" %}
      {% set pkg_url = [pkg_url_base, 'Amazon']|join('/') %}
    {% elif grains['os']=="Centos" %}
      {% set pkg_url = [pkg_url_base, 'EL', pkg_maj_ver]|join('/') %}
    {% else %}
      {% set pkg_url = [pkg_url_base, 'EL', '7']|join('/') %}
    {% endif %}
```

perform a nested IF under each OS/OS Family example 
```
{% elif grains['os']=="CentOS" %} 
{% if grain['osmajorrelease'] = 7 and pillar['ts_agent_version'].startswith('2.')) %}}
{% set pkg_url_base = 'https://pkg.threatstack.com/v2' %}
{% else %}
{% set pkg_url_base = 'https://pkg.threatstack.com' %}
```

rinse and repeat for all os families using linked document above so the 2.x agents can not be installed on systems that do not support the 2.x agent.

**Comment by ssoto2** [comment]
additionally, remove 

    {% if install_agent2 == True %}
      {% set pkg_url_base = 'https://pkg.threatstack.com/v2' %}
    {% else %}
      {% set pkg_url_base = 'https://pkg.threatstack.com' %}
    {% endif %}

**Comment by amberb617** [comment]
Thank you for the feedback @ssoto2 I will review with the engineering team
