### ISSUE TITLE
Add support for Debian 11 "bullseye"

### ISSUE THREAD

**Issue by oioki** [threatstack/threatstack-formula#35]
I am getting this error while installing `threatstack-agent` on the latest Debian 11 (released on August 14th) using this formula:
```
[ERROR   ] stderr: E: Failed to fetch https://pkg.threatstack.com/v2/Ubuntu/dists/bullseye/InRelease  403  Forbidden [IP: 65.8.49.125 443]
E: The repository 'https://pkg.threatstack.com/v2/Ubuntu bullseye InRelease' is not signed.
```
Do you have a target date when this will be available?

**Comment by olhado** [comment]
Hello @oioki,

The Threat Stack agent currently doesn't support Debian 11, so there isn't anything this formula can do. I'd reach out to your Customer Support Manager here at Threat Stack to let them know about your need for a Debian 11 package,

**Comment by oioki** [comment]
This is now working:
```
$ curl -i https://pkg.threatstack.com/v2/Ubuntu/dists/bullseye/InRelease
HTTP/2 200 
content-type: binary/octet-stream
content-length: 4719
date: Thu, 23 Jun 2022 20:43:56 GMT
last-modified: Mon, 16 May 2022 15:08:01 GMT
...
```
